add remark
AY2122S1-CS2103T-W08-3/tp pull request #30
Opened 2021-09-23 05:50 UTC by ngchisern

* adds 'remark' field to the Person class
* update add command to support remark field 
* update edit command to support remark field 
* update the storage to store the remark field

2021-09-25 06:30 UTC, GnohChengYi requested changes
Hey, I like how clean your code is 👍 .
However, you forgot to change some keywords (especially in the comments) to `Remark`. 
Also, would it be better to have a space at the start of comments e.g. `// a comment` instead of `//a comment`, so that there are consistent with most other comments?

2021-09-25 06:30 UTC, GnohChengYi commented on src/main/java/seedu/address/model/person/Remark.java
> + * Represents a Person's name in the address book.
```suggestion
 * Represents a Person's remark in the address book.
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/main/java/seedu/address/model/person/Remark.java
> +     * Returns true if a given string is a valid name.
```suggestion
     * Returns true if a given string is a valid remark.
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    public static final String INVALID_REMARK_DESC = " " + PREFIX_REMARK + "^happy"; // '^' not allowed in tags
```suggestion
    public static final String INVALID_REMARK_DESC = " " + PREFIX_REMARK + "^happy"; // '^' not allowed in remarks
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
> +        //different remark -> false
```suggestion
        // different remark -> false
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> +        //multiple remarks - last remark accepted
```suggestion
        // multiple remarks - last remark accepted
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
> +        assertParseFailure(parser, "1" + INVALID_REMARK_DESC, Remark.MESSAGE_CONSTRAINTS); //invalid remark
```suggestion
        assertParseFailure(parser, "1" + INVALID_REMARK_DESC, Remark.MESSAGE_CONSTRAINTS); // invalid remark
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
> +        //remark
```suggestion
        // remark
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/model/person/RemarkTest.java
> +    public void constructor_invalidName_throwsIllegalArgumentException() {
```suggestion
    public void constructor_invalidRemark_throwsIllegalArgumentException() {
```

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/model/person/RemarkTest.java
> +        assertTrue(Remark.isValidRemark("David Roger Jackson Ray Jr 2nd")); // long remarks
Should the `name`s be `remark`? Check the comments and method name.

2021-09-25 06:30 UTC, GnohChengYi commented on src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
> +                        INVALID_REMARK, VALID_TAGS);
```suggestion
        JsonAdaptedPerson person = new JsonAdaptedPerson(VALID_NAME, VALID_PHONE, VALID_EMAIL,
                VALID_ADDRESS, INVALID_REMARK, VALID_TAGS);
```

Would it be better to make the style consistent?

2021-09-25 07:50 UTC, ngchisern commented
made changes in line with Cheng Yi's comments

2021-09-26 08:10 UTC, GnohChengYi approved these changes
LGTM!

2021-09-26 08:24 UTC, merged